---
name: Geo-IATA
version: 0.0.1
author:
  - 'Joerg Meltzer <joerg <at> joergmeltzer.de>'
abstract: Lookup Airport Codes
license: perl
resources:
  license: ~
requires:
  DBD::SQLite: 0
  DBI: 0
  Test::More: 0
  version: 0
provides:
  Geo::IATA:
    file: lib/Geo/IATA.pm
    version: 0.0.1
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
